name: Bump version

on:
  push:
    branches:
      - "main"

env:
  MERGE_BACK_TO_DEVELOP: true
  DEVELOP_BRANCH: "develop"
  MAIN_BRANCH: "main"

jobs:
  bump-version-and-changelog:
    name: Bump version and generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_sha: ${{ steps.get-sha.outputs.sha }}
    # Skip this job if the commit message starts with 'bump:' as it's already a bump commit
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') && !contains(github.event.head_commit.message, 'Initial commit') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Configure Git bot
        uses: ./.github/actions/config-git-bot

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check if nothing to bump
        id: check_bump
        run: |
          next_version=$(uvx --from commitizen cz bump --get-next --yes)
          echo "next_version=$next_version" >> $GITHUB_OUTPUT
          if [ -z "$next_version" ]; then
            exit 1
          fi
        continue-on-error: true

      - name: Check if duplicate release
        if: ${{ steps.check_bump.outcome == 'success' }}
        id: check_duplicate
        run: |
          tag_exists=$(git tag -l v${{ steps.check_bump.outputs.next_version }})
          echo "tag_exists=$tag_exists" >> $GITHUB_OUTPUT
          if [ -n "$tag_exists" ]; then
            exit 1
          fi

      - name: Bump version and generate changelog
        if: ${{ steps.check_duplicate.outcome == 'success' }}
        id: bump
        run: |
          uvx --from commitizen cz bump --yes --changelog --changelog-to-stdout --git-output-to-stderr > body.md

      - name: push bump commit
        if: ${{ steps.bump.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_ACCESS_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Backpoint to development
        if: ${{ env.MERGE_BACK_TO_DEVELOP == 'true' }}
        uses: ./.github/workflows/backpoint.yml
        with:
          target-ref: ${{ env.DEVELOP_BRANCH }}
